#!/usr/bin/env python3
import random
import sys


import Bio.Seq
import Bio.SeqFeature
import Bio.SeqIO
import Bio.SeqRecord
import Bio.Alphabet.IUPAC


random.seed(0)


class Padding:

    def __init__(self, sequence=None):
        self.sequence = sequence


class Gene:

    def __init__(self, name, strand):
        self.name = name
        self.strand = strand

        if self.name not in genes:
            raise ValueError(f'{self.name} not in genes list')
        self.gene = genes[self.name]

        self.start_contig = int()
        self.end_contig = int()
        self.contig = str()


# Gene data
genes = {
    'ampc': {
        'seq': ('ATGTTCAAAACGACGCTCTGCGCCTTATTAATTACCGCCTCTTGCTCCACATTTGCTGCCCCTCAACAAA'
                'TCAACGATATTGTGCATCGCACAATTACCCCGCTTATAGAGCAACAAAAGATCCCGGGTATGGCGGTGGC'
                'GGTAATTTATCAGGGTAAACCTTATTACTTTACCTGGGGCTATGCGGACATCGCCAAAAAGCAGCCCGTC'
                'ACACAGCAAACGTTGTTTGAGTTAGGTTCGGTCAGCAAAACATTTACTGGCGTGCTTGGTGGCGACGCTA'
                'TTGCTCGAGGGGAAATCAAGTTAAGCGATCCCACAACAAAATACTGGCCTGAACTTACCGCTAAACAGTG'
                'GAATGGGATCACACTATTACATCTCGCAACCTACACTGCTGGCGGCCTGCCATTGCAGGTGCCGGATGAG'
                'GTGAAATCCTCAAGCGACTTGCTGCGCTTCTATCAAAACTGGCAGCCTGCATGGGCTCCAGGAACACAAC'
                'GTCTGTATGCCAACTCCAGTATCGGTTTGTTCGGCGCACTGGCTGTGAAGCCGTCTGGTTTGAGTTTTGA'
                'GCAGGCGATGCAAACTCGTGTCTTCCAGCCACTCAAACTCAACCATACGTGGATTAATGTACCGCCCGCA'
                'GAAGAAAAGAATTACGCCTGGGGATATCGCGAAGGTAAGGCAGTGCATGTTTCGCCTGGGGCGTTAGATG'
                'CTGAAGCTTATGGTGTGAAGTCGACCATTGAAGATATGGCCCGCTGGGTGCAAAGCAATTTAAAACCCCT'
                'TGATATCAATGAGAAAACGCTTCAACAAGGGATACAACTGGCACAATCTCGCTACTGGCAAACCGGCGAT'
                'ATGTATCAGGGCCTGGGCTGGGAAATGCTGGACTGGCCGGTAAATCCTGACAGCATCATTAACGGCAGTG'
                'ACAATAAAATTGCACTGGCAGCACGCCCCGTAAAAGCGATTACGCCCCCAACTCCTGCAGTACGCGCATC'
                'ATGGGTACATAAAACAGGGGCGACCGGCGGATTTGGTAGCTATGTCGCGTTTATTCCAGAAAAAGAGCTG'
                'GGTATCGTGATGCTGGCAAACAAAAACTATCCCAATCCAGCGAGAGTCGACGCCGCCTGGCAGATTCTTA'
                'ACGCTCTACAGTAA')
    },
    'sul1': {
        'seq': ('GTGGGGCTTTGTAGGTATGGGGCTCATAATTGCTGCCTTTTTGCTCGCCCGATCCCCATCGTGGAAGTCG'
                'CTGCGGAGGCCGACGCCATGGTGACGGTGTTCGGCATTCTGAATCTCACCGAGGACTCCTTCTTCGATGA'
                'GAGCCGGCGGCTAGACCCCGCCGGCGCTGTCACCGCGGCGATCGAAATGCTGCGAGTCGGATCAGACGTC'
                'GTGGATGTCGGACCGGCCGCCAGCCATCCGGACGCGAGGCCTGTATCGCCGGCCGATGAGATCAGACGTA'
                'TTGCGCCGCTCTTAGACGCCCTGTCCGATCAGATGCACCGTGTTTCAATCGACAGCTTCCAACCGGAAAC'
                'CCAGCGCTATGCGCTCAAGCGCGGCGTGGGCTACCTGAACGATATCCAAGGATTTCCTGACCCTGCGCTC'
                'TATCCCGATATTGCTGAGGCGGACTGCAGGCTGGTGGTTATGCACTCAGCGCAGCGGGATGGCATCGCCA'
                'CCCGCACCGGTCACCTTCGACCCGAAGACGCGCTCGACGAGATTGTGCGGTTCTTCGAGGCGCGGGTTTC'
                'CGCCTTGCGACGGAGCGGGGTCGCTGCCGACCGGCTCATCCTCGATCCGGGGATGGGATTTTTCTTGAGC'
                'CCCGCACCGGAAACATCGCTGCACGTGCTGTCGAACCTTCAAAAGCTGAAGTCGGCGTTGGGGCTTCCGC'
                'TATTGGTCTCGGTGTCGCGGAAATCCTTCTTGGGCGCCACCGTTGGCCTTCCTGTAAAGGATCTGGGTCC'
                'AGCGAGCCTTGCGGCGGAACTTCACGCGATCGGCAATGGCGCTGACTACGTCCGCACCCACGCGCCTGGA'
                'GATCTGCGAAGCGCAATCACCTTCTCGGAAACCCTCGCGAAATTTCGCAGTCGCGACGCCAGAGACCGAG'
                'GGTTAGATCATGCCTAG')
    },
    'secA': {
        'seq': ('ATGAGCATTTTAACAAGAATTTTTGGTAGTCGTAATGAACGCGTTTTACGTAAATTAAAAAAACAAGTCG'
                'TAAAAATTAATAAAATGGAGCCTGCTTTTGAGGCATTAAGTGATGATGAATTAAAAGCAAAAACACAAGA'
                'GTTTCGTGATCGTTTAAGTGGTGGCGAAACTTTGCAACAAATTTTACCAGAAGCATTCGCAACGGTACGC'
                'GAAGCAAGTAAGCGTGTGCTTGGTATGCGCCATTTTGATGTTCAGCTTATCGGTGGGATGGTATTGACTA'
                'ACCGCTGTATCGCAGAAATGCGTACTGGTGAAGGTAAAACATTAACGGCGACTTTGCCTTGTTATTTAAT'
                'CGCACTTGAAGGTAAAGGCGTTCACGTGGTAACCGTGAATGATTATCTTGCTCGCCGAGATGCAGAAACA'
                'AACCGTCCGTTATTTGAATTTTTAGGCATGAGTGTAGGCGTCAATATTCCTGGTTTATCGCCAGAAGAAA'
                'AACGTGCAGCTTATGCGGCAGATATTACTTATGCAACCAATAGTGAACTTGGTTTTGATTATTTACGTGA'
                'CAACTTAGCCCACTCAAAAGAAGAGCGTTTCCAACGTACTTTAGGCTATGCGTTGGTGGATGAAGTGGAT'
                'TCTATCTTAATCGATGAAGCGCGTACGCCATTGATTATTTCTGGTCAGGCAGAAAACAGTTCAGAGCTTT'
                'ATATTGCGGTAAATAAATTGATCCCAAGTTTAATTAAACAAGAAAAAGAAGATACGGAAGAATATCAAGG'
                'AGAGGGCGATTTCACTTTAGATTTGAAATCTAAACAAGCGCATTTAACCGAACGTGGTCAAGAAAAAGTA'
                'GAAGATTGGTTAATTGCACAAGGTTTAATGCCTGAGGGGGACTCTTTGTATTCTCCTAGTCGAATTGTAT'
                'TGCTTCATCACGTTATGGCTGCATTGCGTGCGCACACATTGTTTGAAAAAGATGTCGATTACATTGTGAA'
                'GGACGGTGAAATCGTGATTGTTGATGAACACACTGGTCGTACAATGGCGGGGCGTCGTTGGTCAGATGGT'
                'TTGCACCAAGCCATTGAGGCAAAAGAAGGGGTGGATGTTAAGAGCGAAAACCAAACTGTTGCATCAATTT'
                'CTTACCAAAACTACTTCCGTTTATATGAACGTCTTGCGGGTATGACGGGGACTGCGGATACCGAAGCATT'
                'TGAGTTCCAACAAATTTATGGCTTGGAAACTGTTGTAATTCCAACAAATCGTCCAATGATTCGTGATGAT'
                'CGCACTGATGTGATGTTTGAAAATGAACAATATAAATTTAATGCGATTATTGAAGACATTAAAGATTGTG'
                'TAGAACGCCAGCAACCAGTATTAGTGGGGACGATTTCAGTCGAAAAATCAGAAGAATTATCTAAAGCGTT'
                'AGATAAAGCAGGTATAAAACACAATGTGTTGAATGCGAAATTCCACCAACAAGAAGCGGAAATCGTGGCA'
                'GAAGCAGGATTTCCTAGCGCAGTGACTATCGCAACGAATATGGCGGGTCGAGGTACGGATATTATTCTTG'
                'GCGGTAACTGGAAAGCGCAGGCTGCCAAATTAGAAAATCCAACTCAAGAACAAATTGAAGCCCTTAAAGC'
                'AGAGTGGGAGAAAAACCACGAAATTGTAATGAAAGCGGGTGGGTTGCATATTATCGGTACAGAGCGTCAC'
                'GAATCTCGCCGTATTGATAACCAGTTGCGCGGTCGTTCTGGGCGTCAAGGTGACCCCGGTTCTTCTCGTT'
                'TCTATCTTTCTTTGGAAGATGGTTTAATGCGCATTTATTTGAATGAGGGTAAGCTCAATTTAATGCGTAA'
                'AGCGTTCACGGTAGCAGGCGAGGCAATGGAGTCGAAAATGTTGGCGAAAGTGATTGCATCTGCTCAAGCA'
                'AAAGTTGAGGCGTTCCATTTTGATGGCCGTAAAAACCTACTTGAATATGATGATGTGGCAAATGACCAAC'
                'GTCACGCGATTTATGAGCAACGCAATCATTTGCTTGATAATGATGATATTTCTGAAACTATCAACGCTAT'
                'TCGCCACGATGTGTTTAATGGTGTGATTGATCAATATATTCCACCACAATCTTTGGAAGAACAATGGGAT'
                'ATTAAAGGGCTTGAAGAACGTTTATCTCAAGAGTTTGGTATGGAATTACCGATTTCTAATTGGTTGGAAG'
                'AAGATAATAATCTTCACGAAGAAAGTTTGCGCGAACGCATTGTGGAAATTGCAGAAAAGGAATACAAAGA'
                'AAAAGAGGCTTTGGTTGGCGAAGACGCTATGCGCCATTTTGAAAAAGGTGTTATGTTGCAAACCTTAGAT'
                'GAACTTTGGAAAGAACACTTAGCTTCGATGGATTATTTACGCCAAGGTATTCATTTACGTGGCTATGCCC'
                'AAAAAGATCCAAAACAAGAGTATAAAAAAGAATCTTTCCGTATGTTTACGGAAATGTTGGATTCTTTAAA'
                'ACACCAGGTTATCACGGCTTTAACCCGTGTACGTGTGCGTACTCAAGAAGAAATGGAAGAAGCTGAACGT'
                'GCTCGTCAAGAAATGGCAGCACGTATCAATCAAAATAATTTACCTGTGGATGAAAATAGTCAGACAACTC'
                'AAAATTCAGAGACTGAAGATTATTCAGATCGTCGCATTGGTCGCAACGAGCCTTGTCCTTGTGGGTCGGG'
                'TAAAAAATATAAGCATTGTCACGGCAGTCGTGTGGCACGCCAGTAA')
    },
    'secD': {
        'seq': ('ATGCTGCAGATTTCGCTTTGGAAGCGTCTTGTCATTCTGGGTCTGTGCCTTGCGGCGCTGATCACGGCGG'
                'CGCCCAACATGTTCTATGCCCGCGTCGAGGGGCATAACGACGCCGTTTCCGCCTTCGAGAAGACCGGGGC'
                'GATGACCGAGACCCAGGAGGCCGCCAAGGCCGCCTGGCCCGACTGGGCGCCCTCGGCGCTGGTCAATCTG'
                'GGGCTTGATCTGCGCGGCGGCGCGCATCTTCTGGCCGAGGTGCATCTGGGCGAGGTCTACAAGGCCCGGA'
                'TGGATGCGCTCTGGCCCGAGGTGCGCAAGGTTCTGGCCGCCGAGCGGGCCACGATCGGCGCGATTCGGCG'
                'CGTGCCCTCGCCCGAAGGCGAGTTGCGCATCCAGATCGGCGAGCGCGCGCAGATCGCCCGCGCCGTCGAA'
                'GTGGCCCGGACGCTGGCCAGCCCGGTGGTCAGCCTGACCGGCGTCGGTCAGACCGACTACGAGGTGACGG'
                'GCGAGGGCGACACCGTCGTCTTCCGGCTGTCGGAGGCCGAAAAGAAAGCCACCGACGATCGCACCATGCA'
                'GCAATCGCTGGAAATCGTGCGTCGGCGCGTCGATGCGGCGGGCACGCGCGAACCCACGATCATGCGCGAA'
                'GGCACCGACCGCATCCTGATCGAAGTGCCCGGCATCGGCTCGGCGCAGGAGCTGAAGGATCTGATCGGCA'
                'CCACCGCCAAGCTGACCTTCCATCCGGTGCTCAGCACGACCTCGAACCCGAATGCGCCGGTCGCCTCGGG'
                'CAATGAACTTCTGCCCGATGCCGAACGGCAGGGGCTTTATCACCTGCTGGACGAGGTTCCGGTGGTGACG'
                'GGCGACGATCTGACCGATGCGCGCCCGACCACCGACGACAACGGCGCCCCGGCGGTGTCGTTCCGCTTCA'
                'ATGTCAGCGGCGCCCGGGCCTTTGGCGATTACACCGCCGGTCATATCGGAGAGCCCTTCGCCATCGTTCT'
                'GGACGGCAAGGTGATTTCGGCACCGACGATCCAGGCGCATATCGCGGGCGGATCGGGGATCATCACCGGC'
                'CGTTTCAGCATCGAGGAAGCCACGGATCTGGCGCTGCTTTTGCGCGCGGGCGCCCTGCCTGCGGGGATGA'
                'CCTTCCTTGAGGAACGCACGATCGGGCCGGAACTGGGCGCCGACAGCGTCAAGGCGGGGATGGTCGCCTC'
                'GGTGATCGGCTTCGTCGCGGTCGTGGCCTACATGATCGCCTCCTACGGGCTTTTCGGCTTCTTTTCCTCG'
                'GTGGCGCTGTTCATCAACATTGCCTTCATCTTCGCCGTGATGGGCGCGATCGGCGGCACGATGACCCTGC'
                'CCGGGATCGCCGGGATCGTGCTGACCATCGGCACCTCGGTCGATGCCAACGTGCTGATCTACGAACGCAT'
                'GCGCGAGGAAATCCGGTCGGGCAAATCGCCCGTGCGCGCGATCGAGCTGGGCTTTGACAAGGCGATGTCG'
                'GCGATCATCGACGCGAACGTGACCTCGTTCCTGTCCTCGGCGATCCTGTTCGTGCTGGGGGCCGGGCCGG'
                'TGCGCGGCTTTGCCGTGACCACGATGATCGGCATCGCCGCCTCGATCTTCACCGCGATCTGGGTGGTCCG'
                'GCTGATGATCGTCATCTGGTACGGCTGGCGTCGTCCCAAGACCATCGTCATCTGA')
    },
    'mukB': {
        'seq': ('ATGATTGAACGCGGTAAATTTCGCTCACTGACGCTGATTAACTGGAACGGCTTTTTTGCCCGAACTTTTG'
                'ACCTTGACGAGCTGGTCACGACGCTTTCTGGCGGTAACGGGGCGGGTAAATCCACCACCATGGCGGCGTT'
                'CGTTACGGCGCTGATCCCCGACCTGACCCTGCTGCATTTCCGTAACACTACGGAAGCCGGGGCCACCAGC'
                'GGTTCGCGCGATAAAGGTCTGCACGGTAAGCTGAAAGCGGGTGTCTGTTATTCGATGCTCGACACCATTA'
                'ACTCGCGCCACCAGCGCGTGGTGGTCGGTGTGCGTCTGCAACAGGTTGCCGGACGCGATCGTAAAGTGGA'
                'TATCAAGCCGTTTGCCATTCAGGGACTGCCGATGTCGGTGCAGCCGACACAGCTGGTGACCGAAACCCTG'
                'AACGAACGCCAGGCGCGCGTGCTGCCGCTTAACGAGCTGAAAGACAAGCTCGAGGCGATGGAAGGCGTGC'
                'AGTTTAAACAGTTCAACTCCATTACTGATTACCACTCGCTGATGTTCGATCTGGGCATCATCGCGCGTCG'
                'TCTGCGCTCCGCATCTGACCGTAGCAAATTCTATCGTCTGATCGAAGCTTCGCTGTATGGCGGGATCTCC'
                'AGTGCCATTACCCGTTCTCTGCGCGACTACCTGTTGCCAGAAAACAGCGGCGTGCGTAAAGCGTTCCAGG'
                'ACATGGAAGCGGCGCTGCGTGAAAACCGTATGACGCTGGAAGCGATTCGTGTCACCCAGTCGGACCGCGA'
                'CCTGTTTAAGCATCTGATCAGCGAAGCCACCAACTACGTGGCGGCGGACTACATGCGTCACGCCAACGAG'
                'CGCCGTGTCCATCTCGACAAAGCCCTGGAGTTTCGTCGCGAGCTACATACTTCGCGTCAGCAACTGGCGG'
                'CTGAGCAGTACAAACACGTCGATATGGCGCGTGAGCTGGCAGAGCACAACGGTGCCGAAGGCGATCTGGA'
                'AGCGGATTATCAGGCGGCCAGTGATCACCTGAACCTGGTGCAAACCGCACTGCGTCAGCAGGAGAAGATC'
                'GAACGCTACGAAGCGGATCTCGATGAGCTGCAGATCCGTCTGGAAGAGCAAAATGAAGTGGTGGCAGAAG'
                'CCATCGAACGCCAGCAAGAGAATGAGGCTCGTGCGGAAGCTGCCGAACTGGAAGTGGACGAGCTGAAAAG'
                'CCAGCTTGCTGACTACCAGCAGGCGCTGGACGTCCAGCAAACGCGCGCGATCCAGTATAACCAGGCGATT'
                'GCTGCGCTTAATCGTGCCAAAGAACTGTGCCATCTGCCGGACTTAACCGCCGACTGCGCCGCCGAATGGC'
                'TGGAAACCTTCCAGGCGAAAGAGCTGGAAGCGACTGAAAAAATGCTCTCTCTTGAGCAGAAAATGAGCAT'
                'GGCGCAAACCGCGCACAGCCAGTTTGAGCAGGCTTATCAGCTGGTGGTGGCAATCAACGGCCCACTGGCG'
                'CGTAACGAGGCGTGGGATGTCGCTCGCGAACTATTGCGCGAAGGGGTCGATCAGCGTCACCTGGCAGAGC'
                'AGGTTCAGCCGCTGCGGATGCGATTAAGCGAACTGGAACAGCGTCTACGCGAGCAGCAAGAAGCTGAGCG'
                'TCTGCTGGCAGATTTCTGCAAACGTCAGGGCAAGAATTTTGATATCGACGAACTGGAAGCCCTGCATCAG'
                'GAACTGGAAGCACGCATTGCCTCTCTTTCCGATAGCGTGTCTAACGCCCGTGAAGAGCGCATGGCACTGC'
                'GCCAGGAGCAGGAACAGCTGCAGTCTCGCATTCAGAGTTTGATGCAGCGTGCGCCGGTTTGGCTGGCAGC'
                'GCAAAACAGTCTCAACCAGTTGAGCGAACAGTGCGGCGAAGAGTTTACCTCCAGCCAGGACGTCACCGAA'
                'TATCTGCAACAGTTGCTGGAGCGTGAGCGAGAGGCGATTGTTGAACGCGATGAAGTGGGCGCGCGCAAAA'
                'ACGCCGTCGATGAAGAGATCGAACGTTTAAGCCAGCCTGGCGGCTCTGAAGATCAGCGTCTGAACGCGCT'
                'GGCGGAGCGTTTTGGTGGTGTGCTGCTGTCAGAAATTTATGACGACGTTAGCCTGGAAGATGCGCCGTAC'
                'TTCTCAGCGCTGTATGGCCCGTCACGCCACGCCATCGTGGTGCCAGATCTGTCACAGGTAACTGAACACC'
                'TGGAAGGCTTGACCGATTGCCCGGAAGATCTCTATCTGATCGAAGGAGATCCGCAGTCATTCGATGACAG'
                'CGTGTTCAGCGTTGATGAGCTGGAAAAAGCGGTAGTGGTGAAAATCGCCGATCGTCAGTGGCGTTATTCA'
                'CGTTTCCCGGAAGTGCCGCTGTTTGGTCGTGCTGCGCGTGAAAGCCGTATTGAAAGCCTCCATGCCGAGC'
                'GTGAAGTGCTTTCCGAACGCTTCGCCACGCTCTCCTTTGATGTACAGAAAACTCAGCGTCTGCATCAGGC'
                'GTTCAGCCGCTTTATCGGCAGTCATCTGGCGGTTGCGTTTGAGTCTGACCCGGAAGCAGAAATCCGTCAA'
                'CTGAACAGCCGTCGCGTCGAACTGGAGCGGGCGTTAAGTAATCATGAAAATGATAACCAGCAGCAGCGTA'
                'TTCAGTTTGAGCAGGCGAAAGAGGGCGTTACGGCGCTGAACCGCATTCTGCCGCGTCTCAACCTGTTGGC'
                'TGATGACAGCCTGGCGGATCGCGTCGATGAAATCCGCGAACGTCTGGATGAAGCCCAGGAAGCCGCGCGT'
                'TTTGTTCAGCAGTTTGGCAATCAACTGGCGAAACTGGAACCGATTGTTTCGGTATTGCAGAGCGACCCGG'
                'AACAGTTCGAACAGTTAAAAGAAGATTACGCGTACTCTCAGCAGATGCAGCGCGATGCCCGTCAGCAGGC'
                'GTTTGCCCTGACGGAAGTGGTGCAGCGTCGTGCGCACTTTAGCTATTCTGACTCGGCAGAAATGCTTAGC'
                'GGTAACAGCGATCTCAACGAAAAACTGCGTGAACGTCTGGAACAGGCGGAAGCGGAGCGTACCCGCGCTC'
                'GCGAAGCGTTGCGCGGTCACGCAGCGCAGTTGAGTCAGTACAACCAGGTGCTGGCTTCGCTGAAAAGTTC'
                'TTACGACACCAAAAAAGAGCTACTCAACGATCTGCAACGTGAATTGCAGGATATCGGCGTGCGTGCTGAT'
                'AGCGGGGCAGAAGAGCGGGCGCGTATTCGCCGTGACGAGCTGCATGCGCAACTGAGCAATAACCGTTCAC'
                'GCCGCAATCAACTGGAAAAAGCGCTTACCTTCTGCGAAGCGGAGATGGACAACCTGACCCGCAAACTGCG'
                'CAAGCTGGAGCGGGATTACTTTGAGATGCGCGAGCAGGTAGTGACCGCCAAAGCGGGCTGGTGTGCGGTG'
                'ATGCGCATGGTGAAAGATAACGGCGTTGAGCGCCGCTTACACCGTCGTGAGCTGGCTTATCTCTCCGCTG'
                'ATGATTTGCGTTCCATGTCGGATAAGGCGTTAGGTGCGCTGCGTCTGGCGGTGGCGGATAACGAACATCT'
                'GCGCGACGTGCTGCGCATGTCGGAAGATCCGAAACGTCCGGAGCGTAAAATTCAGTTCTTCGTGGCGGTT'
                'TATCAGCATCTGCGTGAACGTATTCGTCAGGATATTATTCGTACCGATGATCCGGTGGAAGCTATCGAAC'
                'AGATGGAGATTGAACTTAGCCGTCTGACCGAAGAATTAACCTCCCGTGAACAGAAACTGGCGATCAGTTC'
                'CCGCAGCGTGGCGAACATCATTCGCAAAACCATTCAGCGCGAGCAGAACCGTATCCGTATGCTCAACCAG'
                'GGGTTGCAGAACGTATCGTTTGGTCAGGTGAACAGCGTGCGTCTCAACGTGAACGTGCGTGAAACGCACG'
                'CCATGCTACTGGATGTGCTCTCTGAACAGCACGAGCAGCATCAGGATCTGTTTAACAGCAACCGTTTGAC'
                'CTTCTCGGAAGCGCTGGCGAAACTGTATCAACGTCTTAACCCGCAGATTGATATGGGGCAGCGCACGCCG'
                'CAGACCATCGGTGAAGAACTGCTGGATTACCGCAACTATCTGGAAATGGAAGTTGAGGTTAACCGTGGTT'
                'CCGATGGCTGGCTGCGCGCAGAGTCTGGTGCATTGTCGACCGGTGAGGCGATTGGTACCGGTATGTCGAT'
                'TCTGGTGATGGTGGTACAAAGCTGGGAAGATGAATCTCGCCGCCTGCGCGGTAAAGATATCTCTCCTTGC'
                'CGCCTGCTGTTCCTCGATGAAGCAGCGCGACTGGATGCTCGTTCTATCGCCACGCTGTTTGAATTGTGTG'
                'AGCGTTTGCAAATGCAACTCATCATCGCAGCGCCGGAAAATATCAGCCCGGAGAAAGGCACCACCTATAA'
                'ACTGGTGCGTAAAGTCTTCCAGAATACCGAACACGTTCATGTCGTCGGCCTGCGAGGATTTGCGCCGCAA'
                'CTCCCTGAAACGCTTCCAGGAACTGACGAAGCGCCTTCTCAGGCGAGTTAA')
    },
    'plsB': {
        'seq': ('ATGTCCGGCTGGCAACGAATTTACTATAAATTACTGAATTTACCATTACAGGTGCTGGTAAAAAGCAAGTCTATTCCGGC'
                'AGAGCCTGCCCAGGAATTAGGACTCGATACCTCGCGTCCGGTCATGTACGTCCTGCCCTATAATTCGAAGGCAGACCTGC'
                'TGACGCTGCGCGCCCAATGCCTGGCGCATGATTTACCTGACCCGCTTGAACCGCTGGAAATCGACGGCGCCCTGCTGCCG'
                'CGTTACGTATTCATCCACGGTGGGCCGCGCGTATTTACTTATTACACGCCAAAAGAAGAGTCCATCAAGCTGTTCCACGA'
                'TTACCTCGATCTGCACCGCAACCATCCGGACCTCGATGTGCAAATGGTGCCGGTTTCGGTCATGTTCGGCCGTTCGCCGG'
                'GTCGCGAGAAAGGAGAAGTCAATCCGCCGCTGCGGATGCTGAACGGCATTCAGAAATTTTTCGCCGTCTCCTGGCTCGGC'
                'CGCGACAGCTTCGTGCGCTTCTCGCCGTCCGTTTCGCTGCGCCGCATGGCGGATGAGCACGGTACCGATAAGATCATCGC'
                'CCAGAAGCTGGCTCGCGTCGCTCGCATGCATTTTGCCCGCCAGCGGCTGGCCGCCGTTGGCCCGCGTCTGCCGGCCCGCC'
                'AGGATCTGTTTAATAAACTGCTGGCCTCGAAAGCGATTGCCCGCGCGGTGGAAGACGAAGCGCGCAGCAAGAAAATTTCG'
                'CACGAGAAGGCACAGCAGAACGCTATCGCGCTGATGGAAGAGATTGCGGCGAACTTCTCATACGAGATGATCCGCCTGAC'
                'CGACCGCATTCTCGGCTTCACCTGGAACCGCCTGTACCAGGGCATCAACGTGCATAACGCCGAGCGCGTACGCCAGCTGG'
                'CGCACGACGGCCATGAAATTGTCTATGTCCCCTGCCACCGCAGCCACATGGACTATCTGCTACTCTCCTACGTCCTGTAC'
                'CATCAGGGGCTGGTCCCTCCGCATATCGCGGCGGGCATCAACCTCAACTTCTGGCCGGCCGGGCCGATCTTCCGCCGCCT'
                'CGGCGCCTTCTTTATTCGCCGCACCTTTAAGGGCAACAAGCTCTATTCCACCGTGTTCCGCGAATACCTTGGCGAACTGT'
                'TCAGCCGCGGCTATTCCGTGGAGTATTTCGTCGAAGGCGGCCGCTCCCGTACCGGCCGCCTGCTCGATCCGAAGACCGGT'
                'ACGCTGTCGATGACCATCCAGGCGATGCTGCGCGGCGGAACCCGACCGATCACCCTGGTGCCGATTTACATCGGCTATGA'
                'GCACGTGATGGAGGTAGGAACCTACGCCAAAGAGCTGCGCGGCGCCACTAAAGAGAAAGAGAGTCTGCCGCAGATGGTGC'
                'GCGGTTTAAGCAAGCTGCGCAACCTGGGCCAGGGTTACGTTAACTTCGGCGAACCGCTGCCGCTGATGACCTATCTTAAC'
                'CAGCATGTGCCGGATTGGCGGGAAGCGATCGACCCGATCGAAGCGGTTCGCCCCTCCTGGCTGACGCCGACGGTGAATAG'
                'CATCGCCGCTGACCTGATGGTGCGCATCAATAACGCCGGCGCGGCCAACGCCATGAACCTGTGCTGTACGGCGCTACTGG'
                'CCTCCCGCCAGCGTTCGCTGACCCGTGAGCAGCTCACCCAGCAGTTAGAGTGCTACCTCGCGCTGCTGCGCAATGTGCCC'
                'TATTCTCCGGATGCGACCGCCCCATCCGCTTCAGCCAGCGAGCTCATCGATCATGCGCTGCAGATGAACAAGTTCGAAGT'
                'GGAGAAGGACACCATTGGCGACATCATCATCCTGCCGCGCGAGCAGGCGGTGCTGATGACCTACTATCGCAACAATATCG'
                'CCCATATGCTGGTGATGCCGTCGCTGTTAGCCGCTCTGGTGACTCAGCATCGTCATCTCAGCCGCGCCGAAGTGCTGCGT'
                'CATGTGGAAACACTCTATCCGTTCCTCAAGGCCGAGCTGTTCCTGCGCTGGGAAAAAGCGGAGCTGGCCGGAGTGGTGGA'
                'TGCGCTGATTGCCGAGATGCTGCGTCAGGAGCTGATCGTCGTCGATGGCGATGTCATGAGCCTCAACCCGTCGCACTCTC'
                'GCTCCCTGCAGCTGCTGGCCGCTGGCGCCCGCGAGACGCTGCAGCGCTATGCCATCACCTTCTGGCTGCTGAGCGCTAAC'
                'CCGGCGATCAACCGCAGCTCGCTGGAAAAAGAGAGTCGCACCGTGGCCCAGCGTCTGTCGGTGCTACACGGCATCAATGC'
                'GCCGGAGTTCTTCGACAAAGCGGTGTTCAGCACCCTGGTGTTGACCCTGCGCGATGAAGGCTATATCAGCGACACCGGCG'
                'ACGCCGAGCCGGAAGAGACCCTGAAGGTTTATCGGATGCTGGCGGACTTGATTACGTCGGATGTCCGACTGACCATTGAG'
                'AGCGTCACGCAGGACGACGCGTAA')
    },
    'dmsA': {
        'seq': ('ATGAAAATTAAAGCCCCTGATGCTTTACTGGCTGCTGAGGTAAGCCGCCGTGGTCTGATGAAAACCACGGCAATAGGCGG'
                'CCTGGCGCTGGCCAGCAACGCACTAACGTTACCTTTTACCCGACTGTCGCATGCTGCCGATACGCCGGCGCCCGCCAGTG'
                'AGAAGGTGGTCTGGAGCGCCTGCACCGTCAACTGCGGTAGCCGTTGCCCGCTGCGCATGCACGTGGTGGATGGCGCGATT'
                'AAATACGTCGAAACCGATAATACCGGTGATGATAACTATGACGGTTTGCACCAGGTCCGCGCCTGCCTGCGTGGGCGTTC'
                'AATGCGCCGCCGGGTCTATAATCCGGACCGTCTGAAGTACCCGATGAAGCGCGTTGGTAAACGCGGTGAGGGCAAGTTCG'
                'AGCAAATCAGCTGGGAAGAGGCGTTGGATACCATCGCCAGCAATATGCAGCGGCTGATTAAAGAGTACGGCAATGAATCC'
                'ATCTATCTGAACTACGGCACCGGCACGCTCGGCGGGACGCTGACCCGCTCCTGGCCGCCGGGGAAAACGCTGATTGCCCG'
                'TCTGATGAACTGCTGCGGCGGCTATCTCAACCATTATGGCGACTATTCATCAGCGCAGATTGCTGCCGGTCTGAATTACA'
                'CCTACGGCGGCTGGGCGGACGGCAACAGCCCATCGGATATTGAAAACAGTCAGCTGGTGGTGCTGTTCGGCAATAACCCC'
                'GGCGAAACGCGGATGAGCGGCGGCGGGGTGACGTACTACCTTGAACAGGCGCGGCAGAAATCCAATGCCCGGATGATAAT'
                'CATCGATCCGCGCTATACCGACACCGGCGCCGGGCGTGAAGATGAATGGATCCCGATTCGTCCTGGGACCGATGCGGCAC'
                'TGGTTTCGGGCCTCGCGTGGGTGATGATCACCGAGAATCTGGTCGATCAGCCGTTCCTCGATAAATACTGCGTGGGATAC'
                'GACGAGAAAACGCTGCCCGCCGGTGCGCCAGCCAATGGTCATTACAAAGCTTACATTCTTGGCCAGGGCACTGACGGTAT'
                'CGCCAAAACGCCGGAGTGGGCCTCGACGATTACCGGTATTCCGCGCGAACGCATTGTTAAACTGGCGCGCGAAATTGCCA'
                'CCGCCAAACCGGCCTATATTAGCCAGGGCTGGGGTCCGCAGCGTCACGCCAACGGTGAGATCGCCACCCGCGCCATCTCA'
                'ATGCTCGCCATTCTGACGGGTAACGTCGGGATCAACGGCGGCAATAGCGGGGCGCGCGAGGGCTCGTATAGTTTGCCTTT'
                'TGAGCGTATGCCGACGCTGGAGAATCCGGTTGAGACCAGTATCTCGATGTTTATGTGGACCGATGCGATTGAGCGCGGCC'
                'CGGAAATGACCGCTCTGCGCGACGGCGTACGCGGTAAAGATAAGCTCGACGTGCCGATCAAAATGATCTGGAACTATGCG'
                'GGCAACTGTCTGATTAACCAGCATTCTGAGATCAACCGGACCCACGAAATCCTGCAGGACGACAAGAAATGCGAGATGAT'
                'TGTGGTCATTGACTGCCATATGACCTCCTCGGCGAAATACGCTGATATTCTGCTGCCGGACTGTACCGCCTCCGAGCAGA'
                'TGGATTTCGCGCTGGATGCCTCCTGCGGCAACATGTCCTACGTTATCTTTGCCGATCAGGCCATCAAGCCGCGCTTTGAA'
                'TGCAAAACCATCTATGAGATGACCAGCGAACTGGCAAAGCGTCTGGGCGTCGAAGAGCAGTTTACCGAGGGCCGTACCCA'
                'GGAAGGCTGGATGCGCTATCTGTATGAGCAGTCGCGCAAAGCGATTCCCGACCTGCCGGATTTCGACACCTTCCGTCAGC'
                'AGGGCATCTATAAGCAGCGCGATCCGCAAGGTCATCATGTGGCCTACAAAGCCTTCCGTGAGGATCCGCAGGCTAATCCG'
                'CTGACCACGCCTTCGGGCAAGATCGAAATTTACTCGCAGGATCTGGCGAAAATCGCGGCCACCTGGGAGCTGCCGGAAGG'
                'GGATGTTATCGATCCGTTGCCGATCTACACCCCGGGTTTCGAAAACTACAACGATCCGCTGACAGCGAAATACCCGCTAC'
                'AGCTCACCGGCTTCCACTATAAATCTCGCGTCCACTCGACCTACGGCAACGTCGATGTGCTGAAGGCCGCTTGTCGGCAG'
                'GAGATGTGGATTAACCCGATCGATGCCCGCAAGCGCGGCATTGCCAACGGCGATCGTATTCGCATCTTCAACGATCGGGG'
                'TGAAGTGCATATCGAAGCGAAGGTGACGCCGCGCATGATGCCGGGCGTCGTCGCGCTGGGGGAAGGGGCCTGGTACAACC'
                'CGGACGCCTCGCGTGTGGATCAGGCGGGCAGCATCAACGTGCTGACCACCCAGCGTCCGTCGCCGCTGGCGAAGGGAAAC'
                'CCGTCGCATACCAACCTCGTTCAGGTTGAGAAGCTGTAA')
    },
    'mrkC': {
        'seq': ('ATGAAGCAGAGGTCATTCTGCCCGGGAAGATTAAGCACCGCGATCGCCATCGCGCTGTGCTGCTTTCCGCCATTTTCCAG'
                'CGGACAGGAAAACCCGGGAACGGTATATCAGTTTAACGACGGCTTTATTGTCGGCAGTCGCGAAAAGGTCGATCTGTCGC'
                'GCTTTTCGACCAGCGCGATTACCGAAGGCACTTACTCCCTTGACGTCTACACCAACGACGAGTGGAAAGGGCGCTACGAT'
                'TTACGCATCGCGCGCGATAAAGATGGTCGGCTGGGCGTCTGCTACACCAAAGCGATGCTGGCCCAATATGGCATCGCGGC'
                'GGAAAAGCTCAATCCGCAGCTGAGCGAGCAGGAGGGCTACTGCGGTAGCCTCAAATCCTGGCGCAACGAAGAAAACGTCA'
                'AAGACAACCTGGTCCAGTCCTCCCTGCGGTTGAACATTTCGGTACCGCAGATCTATGAAGATCAACGCCTGAAAAACTAT'
                'GTCAGCCCGGAGTTCTGGGACAAAGGTATTACCGCGCTCAATCTTGGCTGGATGGCGAACGCCTGGAACAGCCATACCTC'
                'TTCGGTAGGCGGGTCGGATAACAGCAGCGCCTATCTGGGCGTCAACGCCGGTCTGTCGTGGGACGGCTGGCTGCTGAAGC'
                'ACATCGGCAACCTGAACTGGCAGCAGCAGCAGGGTAAAGCGCACTGGAACAGCAACCAGACCTATCTCCAGCGCCCTATC'
                'CCACAGCTCAACTCCATCGTCAGCGGCGGGCAGATTTTCACCAATGGTGAATTTTTCGACACCATCGGTCTGCGCGGGGT'
                'TAATCTTTCCACCGATGACAATATGTTCCCGGACGGCATGCGCTCGTATGCTCCGGAAATTCGCGGCGTGGCGCAGAGCA'
                'ACGCCCTCGTCACCGTGCGCCAGGGCAGCAATATTATCTATCAGACCACCGTTCCGCCCGGACCGTTTACCCTGCAGGAT'
                'GTCTATCCTTCCGGCTATGGCAGCGATCTTGAGGTCTCGGTGAAAGAAGCGGATGGCTCGGTAGAAGTGTTTAGCGTGCC'
                'TTACGCTTCCGTCGCCCAGCTGCTGCGTCCGGGAATGACCCGCTACGCGCTCTCCGCCGGTAAAGTGGACGACAGCGCGC'
                'TGCGCAACAAGCCGATGCTCTATCAGGCGACCTGGCAGCACGGGATCAACAATCTGTTGACCGGCTACACCGGGGTCACC'
                'GGTTTTGACGACTATCAGGCCTTCCTGGTGGGGACAGGGATGAACACCGGCATCGGCGCGCTCTCTTTTGACGTCACCCA'
                'TTCGCGGTTGAAGAGCGATGCCCATGATGACTCGGGTCAGAGCTATCGCGCGACCTTTAACCGCATGTTTACCGATACCC'
                'AGACCAGCATCGTGTTGGCGGCGTATCGCTACTCGACGAAAGGTTATTACAACCTCAACGACGCGCTGTACGCCGTCGAT'
                'CAGGAAAAAAATAGTCGCAGCAACTACACCCTGTGGCGGCAAAAAAACGGCATGACCTTCACGGTGAACCAGAACCTGCC'
                'GGACGGCTGGGGCGGGTTTTATCTCAGCGGCCGTATCTCCGATTACTGGAACCGCTCCGGGACCGAGAAGCAGTATCAGG'
                'TCAGCTACAACAATTCATTTGGTCGTCTCTCCTGGTCGGCGAGCGCGCAGCGCGTCTATACGCCAGACAGCTCCGGTCAT'
                'CGTCGCGACGATCGTATTTCACTCAACTTCAGCTACCCGCTGTGGTTTGGCGATAACCGCACCGCCAACCTGACGTCGAA'
                'CACCTCGTTCAATAACTCGCGCTTTGCCAGCTCGCAGATTGGTATCAACGGTTCGCTGGACAGTGAAAACAACCTTAACT'
                'ACGGCGTGTCGACCACCACCGCCACCGGCGGTCAGCATGATGTGGCGCTCAACGGCAGCTACCGTACGCCATGGACCACC'
                'CTCAACGGCAGCTACAGCCAGGGCGAAGGCTATCGTCAGAGCGGCATTGGCGCCAGCGGGACGATGATCGCCCACAGCGG'
                'CGGCGTGGTGCTCTCACCGGAAAGCGGCTCGACGATGGCCCTGATTGAAGCCAAAGACGCGGCCGGGGCGATGCTTCCGG'
                'GATCGCCGGGCACCCGTGTGGACAGCAATGGTTACGCCATCCTGCCGTATCTGCGCCCGTACCGGATTAACGCCGTGGAA'
                'ATCGACCCGAAAGGCAGCCATGACGACGTGGCCTTCGATCGCACCGTGGCGCAGGTTGTGCCGTGGGAAGGCAGCGTGGT'
                'TAAGGTCGCGTTCGGCACTAAGGTGCAGAACAACCTCACCCTGCAGGCGCGCCAGGCGAACCACGAGCCGTTGCCGTTTG'
                'CGGCAAGTATTTTCTCCCCCGACGGCAAGGAGATCGGCGTTGTCGGCCAGGGCAGCATGATGTTTATCAGCGATGCGAAC'
                'GCCAAACGCGCGATTGTGAAGTGGAGCGGCGGGCAGTGTTCGGTGGATCTGGGACAGCAAACAACAAAGGATAGCGTATG'
                'TCGCTGA')
    }
}


# Genbank layout
layout = {
        'contig_1': (
            Padding('NNNNNNNNNN'),
            Gene(name='ampc', strand=1),
            Padding('NNNNNNNNNN'),
            Gene(name='sul1', strand=1),
            Padding('NNNNTNNNNN'),
            Gene(name='secA', strand=1),
            Padding('NNNNNNNNNG'),
            Gene(name='secD', strand=1),
            Padding('ANNNNNNNNN'),
            Gene(name='mukB', strand=1),
            Padding('NNNNNNNNNN'),
            Gene(name='plsB', strand=-1),
            Padding('NNNNNNNNNN'),
            Gene(name='dmsA', strand=-1),
            Padding('NNNNNNNNNN'),
        ),
        'contig_2': (
            Padding('NNNNNNNNNN'),
            Gene(name='mrkC', strand=-1),
            Padding('NNNNNNNNNN'),
            Padding(''.join(random.choices('ATGC', k=12500))),
            Padding('NNNNNNNNNN'),
        )
}


def main():
    # Create genbank from layout
    gb_records = dict()
    for contig, specs in layout.items():
        sequence_size = 0
        sequence_contig = list()
        for spec in specs:
            if isinstance(spec, Padding):
                spec_sequence = spec.sequence
            elif isinstance(spec, Gene):
                spec_sequence = Bio.Seq.Seq(spec.gene['seq'], Bio.Alphabet.IUPAC.ambiguous_dna)
                if spec.strand == -1:
                    spec_sequence = spec_sequence.reverse_complement()
                # Update Gene instance with position and contig
                spec.start_contig = sequence_size
                spec.end_contig = spec.start_contig + len(spec_sequence)
                spec.contig = contig
            else:
                raise ValueError(f'got back spec type ({spec})')
            sequence_contig.append(str(spec_sequence))
            sequence_size += len(spec_sequence)
        # Create sequence record
        sequence_record = Bio.Seq.Seq(''.join(sequence_contig), Bio.Alphabet.IUPAC.ambiguous_dna)
        gb_records[contig] = Bio.SeqRecord.SeqRecord(seq=sequence_record, id=contig, name=contig)

        # Add features
        gene_counter = 1
        for spec in layout[contig]:
            if not isinstance(spec, Gene):
                continue
            locus_tag = f'{spec.name}'
            quals = {'gene': spec.name, 'locus_tag': locus_tag, 'product': 'not_implemented'}
            start = spec.start_contig
            end = spec.end_contig
            feature_loc = Bio.SeqFeature.FeatureLocation(start=start, end=end, strand=spec.strand)
            feature = Bio.SeqFeature.SeqFeature(location=feature_loc, type='CDS', qualifiers=quals)
            gb_records[contig].features.append(feature)
            gene_counter += 1


    # Print genbank file
    gb_output = [record for record in gb_records.values()]
    Bio.SeqIO.write(gb_output, sys.stdout, 'genbank')


if __name__ == '__main__':
    main()
